from __future__ import annotations

import re
import sys
from functools import partial

with open(sys.argv[1], "r") as f:
    text = f.read()

partialify = partial(re.compile(r"\b([A-Z]\w+)").sub, r"\1Partial")

subs = (
    (r"^type int = float\n", ""),
    (r"(# Generated by .*) on .*", r"\1"),
    (
        r"^(from typing import \([^)]+),\s*TypedDict,\n\)",
        r"\1)\n\nfrom typing_extensions import TypedDict",
    ),
    (
        r"""(?x)
            ^
            (class\ \w+) # m[1]
            (            # m[2]
                \(
                .*?
            )
            (TypedDict)  # m[3]
            (            # m[4]
                \)
                (?s:.)+?
                \n\n\n
            )
        """,
        lambda m: "".join(
            (
                f"{m[0]}",
                f"{m[1]}Partial",
                f"{partialify(m[2])}",
                f"{m[3]}, total=False",
                f"{m[4]}",
            )
        ),
    ),
    (
        r"^(class (?:WKKanaVocabData|WKKanjiData|WKRadicalData|WKVocabData)\([^)]+)",
        r"\1, closed=True",
    ),
    (
        r"^type (WKSubjectData = (?:\((?:.|\n)+?\)|.*|))",
        lambda m: f"{m[0]}\ntype {partialify(m[1])}",
    ),
    (r"^class WKSubject\[T\]", "class WKSubject[T = WKSubjectData]"),
)

result = text
for pat, repl in subs:
    result = re.sub(pat, repl, result, flags=re.M)

with open(sys.argv[1], "w") as f:
    f.write(result)
